# Generated by Django 6.0.3 on 2026-03-24 14:35

import apps.prescriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.FileField(upload_to='prescriptions/', validators=[apps.prescriptions.models.validate_prescription_file]),
        ),
    ]
