# Generated by Django 6.0.3 on 2026-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("painkillers", "Painkillers"),
                    ("antibiotics", "Antibiotics"),
                    ("supplements", "Supplements & Vitamins"),
                    ("chronic", "Chronic Medication"),
                    ("first_aid", "First Aid"),
                    ("skincare", "Skincare"),
                    ("general", "General Health"),
                ],
                default="general",
                max_length=100,
            ),
        ),
    ]
